notAPlayer: '&cOnly players may execute this command!'
noPermission: '&cYou do not have permission to execute this command!'
Locked: '&cThe curse repels this modification!'

Lock:
  itemNull: '&cYou must have an item in your hand to use this command!'
  success: '&aSuccessfully locked your item!'
  alreadyLocked: '&cThis item is already locked!'

Identifiers:
  - "Curse Of Locking"
  - "Locked"