name: ItemLocker
version: 1.0
main: me.border.itemlocker.ItemLocker
api-version: 1.16
author: MrBorder
commands:
  itemlock:
    description: Lock an item.

permissions:
  itemlocker.lock:
    default: op
    description: Allows the player to use /itemlock
  itemlocker.bypass:
    default: op
    description: Allows the player to bypass curse of locking